### PR TITLE
Converted to a module for better integration with other programs

### PR DESCRIPTION
**Pull request by JimScope**

### CODE REVIEW

**Comment by JimScope** [comment]
I will be offline because I live in Cuba and the internet access is dificult and not cheep for cubans. If you have a Job or a simple task and need help contactme at lucia.77@nauta.cu or maybe a very small donation trough ding.com in my phone +53 58099944. Any help is grateful

**Comment by JimScope** [comment]
Consider the pull request

**Comment by Tylersuard** [comment]
Hi there.  Could you explain to me what your code changes do?

**Comment by JimScope** [comment]
Insults are now in json file and access to these is by functions, allowing integration with other programs

**Pull request closed without merging**
